# Generated by Django 4.2.18 on 2025-02-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tournament_participated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tournament_win',
        ),
    ]
