# Generated by Django 4.2.18 on 2025-02-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament',
            field=models.BooleanField(default=False),
        ),
    ]
